import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { StpaGeneratedModule } from './generated/module';
import { STPAScopeProvider } from './stpa-scopeProvider';
import { StpaValidationRegistry, StpaValidator } from './stpa-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type StpaAddedServices = {
    references: {
        STPAScopeProvider: STPAScopeProvider
    },
    validation: {
        StpaValidator: StpaValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type StpaServices = LangiumServices & StpaAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const StpaModule: Module<StpaServices, PartialLangiumServices & StpaAddedServices> = {
    references: {
        ScopeProvider: (injector) => new STPAScopeProvider(injector),
        STPAScopeProvider: (injector) => new STPAScopeProvider(injector)
    },
    validation: {
        ValidationRegistry: (injector) => new StpaValidationRegistry(injector),
        StpaValidator: () => new StpaValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createStpaServices(context?: DefaultModuleContext): StpaServices {
    return inject(
        createDefaultModule(context),
        StpaGeneratedModule,
        StpaModule
    );
}
